spring:
  application:
    name: api-running
  data:
    mongodb:
      database: apirunningtest
      host: localhost
      port: 27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

